News Online/OnlineNews/OnlineNews/Controllers/BackendController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace MovieShop.Controllers.backend
{
    public class BackendController : Controller
    {
        [Authorize(Roles = "superuser,admin")]
        //GET: backend
        public ActionResult Dashboard()
        {
            return View();
        }

    }
}

News Online/OnlineNews/OnlineNews/Controllers/newsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Migrations;
using System.Data.Entity.Validation;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using OnlineNews;
using OnlineNews.Controllers.backend;

namespace OnlineNews.Controllers
{
    public class newsController : Controller
    {
        private OnlineNewsEntities db = new OnlineNewsEntities();
        TextEncryption enctxt = new TextEncryption();
        // GET: news
        public ActionResult Index()
        {
            return RedirectToAction("BackIndex");
        }
        public ActionResult BackIndex()
        {
            TempData["mainHead"] = "News";
            TempData["cardTitle"] = "Manage News";
            TempData["breadcrumb"] = "Manage-News";
            return View("~/Views/news/backend/Index.cshtml");
        }

        // GET: news/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            news news = db.news.Find(id);
            if (news == null)
            {
                return HttpNotFound();
            }
            return View(news);
        }

        // GET: news/Create
        public ActionResult Create()
        {
            TempData["mainHead"] = "News";
            TempData["cardTitle"] = "Manage News";
            TempData["breadcrumb"] = "Manage-News";
            ViewBag.category_id = new SelectList(db.categories, "id", "cname");
            return View("~/Views/news/backend/Create.cshtml");
        }

        // POST: news/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include = "id,newsTitle,newsDescription,category_id,news_img,active,createdby,modifiedby,createdDate,modifiedDate")] news news)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.news.Add(news);
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }

        //    return View(news);
        //}
        public ActionResult Create(HttpPostedFileBase items_img, HttpPostedFileBase trailerUrl, HttpPostedFileBase video)
        {
            string filex = null;
            string imgname = null, imgfilex = null, encryptedName = null, postername = null, posterfilex = null, encryptedposterName = null, videofilename = null, encryptedvideofile = null, videofilex = null;
            try
            {


                if (items_img != null)
                {
                    imgname = System.IO.Path.GetFileNameWithoutExtension(items_img.FileName);
                    filex = System.IO.Path.GetExtension(items_img.FileName);
                    encryptedName = enctxt.TextEncryp(imgname);
                    string imgpath = Server.MapPath("~/Uploads/" + encryptedName);
                    items_img.SaveAs(imgpath + filex);
                }

                if (trailerUrl != null)
                {
                    postername = System.IO.Path.GetFileNameWithoutExtension(trailerUrl.FileName);
                    posterfilex = System.IO.Path.GetExtension(trailerUrl.FileName);
                    encryptedposterName = enctxt.TextEncryp(postername);
                    string posterpath = Server.MapPath("~/Uploads/" + encryptedposterName);
                    trailerUrl.SaveAs(posterpath + posterfilex);
                }

                if (video != null)
                {
                    videofilename = System.IO.Path.GetFileNameWithoutExtension(video.FileName);
                    videofilex = System.IO.Path.GetExtension(video.FileName);
                    if (video.ContentLength < 104857600)
                    {
                        var uploadFilesDir = System.Web.HttpContext.Current.Server.MapPath("~/Uploads/Videos");
                        if (!Directory.Exists(uploadFilesDir))
                        {
                            Directory.CreateDirectory(uploadFilesDir);
                        }

                        encryptedvideofile = enctxt.TextEncryp(videofilename);
                        string vpath = Path.Combine(uploadFilesDir, encryptedvideofile + videofilex);
                        video.SaveAs(vpath);
                    }
                    else
                    {
                        Console.WriteLine("File is too large");
                    }

                }

                news i = new news();
                i.newsTitle = Request.Form["item_name"];
                i.newsDescription = Request.Form["items_description"];
                i.category_id = Convert.ToInt32(Request.Form["category_id"]);
                string username = Session["backUname"].ToString();
                i.createdby = (username != null) ? username : "Admin";
                i.modifiedby = (username != null) ? username : "Admin";
                i.createdDate = DateTime.Now;
                i.modifiedDate = DateTime.Now;
                i.news_img = encryptedName + filex;
                db.news.Add(i);
                db.SaveChanges();
                TempData["mainHead"] = "News";
                TempData["cardTitle"] = "Manage News";
                TempData["breadcrumb"] = "Manage-News";
                return RedirectToAction("BackIndex");
            }
            catch (DbEntityValidationException e)
            {
                foreach (var eve in e.EntityValidationErrors)
                {
                    Debug.WriteLine("Entity of type \"{0}\" in state \"{1}\" has the following validation errors:",
                        eve.Entry.Entity.GetType().Name, eve.Entry.State);
                    foreach (var ve in eve.ValidationErrors)
                    {
                        Debug.WriteLine("- Property: \"{0}\", Value: \"{1}\", Error: \"{2}\"",
                            ve.PropertyName,
                            eve.Entry.CurrentValues.GetValue<object>(ve.PropertyName),
                            ve.ErrorMessage);
                    }
                }
                //throw;
            }
            TempData["mainHead"] = "News";
            TempData["cardTitle"] = "Manage News";
            TempData["breadcrumb"] = "Manage-News";
            return RedirectToAction("Create");

        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            news ms_items = db.news.Find(id);
            if (ms_items == null)
            {
                return HttpNotFound();
            }
            ViewBag.category_id = new SelectList(db.categories, "id", "cname", ms_items.category_id);
            TempData["mainHead"] = "News";
            TempData["cardTitle"] = "Manage News";
            TempData["breadcrumb"] = "Manage-News";
            return View("~/Views/news/backend/Edit.cshtml", ms_items);
        }

        // POST: Categories/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(HttpPostedFileBase items_img, HttpPostedFileBase trailerUrl, HttpPostedFileBase video)
        {
            //ms_items i = new ms_items();
            int id = Convert.ToInt32(Request.Form["id"]);
            var i = (from it in db.news
                     where it.id == id
                     select it).FirstOrDefault();

            string filepath = null;
            string videofilepath = null;
            string posterfilepath = null;
            string imgname = null, imgfilex = null, filex = null, encryptedName = null, postername = null, posterfilex = null, encryptedposterName = null, videofilename = null, encryptedvideofile = null, videofilex = null;

            if (items_img != null)
            {
                filepath = Server.MapPath("~/Uploads/" + items_img.FileName);
            }

            
            try
            {
                if (filepath != null)
                {
                    if (System.IO.File.Exists(filepath))
                    {
                        System.IO.File.Delete(filepath);
                    }
                }

                if (posterfilepath != null)
                {
                    if (System.IO.File.Exists(posterfilepath))
                    {
                        System.IO.File.Delete(posterfilepath);
                    }
                }

                if (videofilepath != null)
                {
                    if (System.IO.File.Exists(videofilepath))
                    {
                        System.IO.File.Delete(videofilepath);
                    }
                }

                if (ModelState.IsValid)
                {

                    if (items_img != null)
                    {
                        imgname = System.IO.Path.GetFileNameWithoutExtension(items_img.FileName);
                        filex = System.IO.Path.GetExtension(items_img.FileName);
                        encryptedName = enctxt.TextEncryp(imgname);
                        string imgpath = Server.MapPath("~/Uploads/" + encryptedName);
                        items_img.SaveAs(imgpath + filex);
                    }


                    i.newsTitle = Request.Form["item_name"];
                    i.newsDescription = Request.Form["items_description"];
                    i.category_id = Convert.ToInt32(Request.Form["category_id"]);

News Online/OnlineNews/OnlineNews/Views/news/backend/Create.cshtml
@model OnlineNews.news

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout_backend.cshtml";
}

<div class="content-wrapper" style="min-height: 512px;">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>@TempData["mainHead"]</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">@TempData["breadcrumb"]</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <!-- left column -->
                <div class="col-md-12">
                    <!-- Form Element sizes -->
                    <div class="card card-success">
                        <div class="card-header">
                            <h3 class="card-title">@TempData["cardTitle"]</h3>
                        </div>
                        <div class="card-body">
                            @using (Html.BeginForm("Create", "news", FormMethod.Post, new { enctype = "multipart/form-data" }))
                            {
                                @Html.AntiForgeryToken()

                                <div class="form-group">
                                    <label class="control-label col-md-2" for="item_name">Title</label>
                                    <div class="col-md-6">
                                        <input class="form-control text-box single-line" id="item_name" name="item_name" type="text" value="" />
                                        <span class="field-validation-valid text-danger" data-valmsg-for="item_name" data-valmsg-replace="true"></span>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="control-label col-md-2" for="items_description">
                                        News Description
                                    </label>
                                    <div class="col-md-10">
                                        <textarea class="form-control text-box single-line" id="items_description" name="items_description" type="text" value=""></textarea>
                                        <span class="field-validation-valid text-danger" data-valmsg-for="items_description" data-valmsg-replace="true"></span>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="control-label col-md-2" for="category_id">Category</label>
                                    <div class="col-md-10">
                                        @Html.DropDownList("category_id", null, "Select Category", htmlAttributes: new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.category_id, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="thumbnail g-logo-img ">
                                        <img id="image" src="~/Uploads/Product_Icon.png" alt="" style="width: 150px; height: 150px;">
                                    </div>
                                    <label class="control-label col-md-2" for="items_img">Banner Image</label>
                                    <div class="input-group">
                                        <div class="custom-file">
                                            <input type="file" class="custom-file-input" id="items_img" name="items_img" onchange="readURL(this);">
                                            <span class="field-validation-valid text-danger" data-valmsg-for="items_img" data-valmsg-replace="true"></span>
                                            <label class="custom-file-label" for="items_img">Choose file</label>
                                        </div>
                                        <div class="input-group-append">
                                            <span class="input-group-text" id="">Upload</span>
                                        </div>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="col-md-offset-2 col-md-10">
                                        <input type="submit" value="Add" class="btn btn-default" />
                                    </div>
                                </div>

                            }
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
                <!--/.col (left) -->
            </div>
            <!-- /.row -->
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
</div>

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

News Online/OnlineNews/OnlineNews/Views/news/backend/Edit.cshtml
@model OnlineNews.news
    @{
        ViewBag.Title = "Edit";
        Layout = "~/Views/Shared/_Layout_backend.cshtml";
    }


<div class="content-wrapper" style="min-height: 512px;">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>@TempData["mainHead"]</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">@TempData["breadcrumb"]</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <!-- left column -->
                <div class="col-md-12">
                    <!-- Form Element sizes -->
                    <div class="card card-success">
                        <div class="card-header">
                            <h3 class="card-title">@TempData["cardTitle"]</h3>
                        </div>
                        <div class="card-body">

                                @using (Html.BeginForm("Edit", "news", FormMethod.Post, new { enctype = "multipart/form-data" }))
                                {
                                    @Html.AntiForgeryToken()

                                    <div class="form-horizontal">
                                        <h4>ms_items</h4>
                                        <hr />
                                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                        @Html.HiddenFor(model => model.id)
                                        <input type="hidden" name="item_id">
                                        <div class="form-group">
                                            <label class="control-label col-md-2" for="item_name">Title</label>
                                            <div class="col-md-6">
                                                <input class="form-control text-box single-line" id="item_name" name="item_name" type="text" value="@Model.newsTitle" />
                                                <span class="field-validation-valid text-danger" data-valmsg-for="item_name" data-valmsg-replace="true"></span>
                                            </div>
                                        </div>
                                
                                        <div class="form-group">
                                            <label class="control-label col-md-2" for="items_description">News Description</label>

                                            <div class="col-md-10">
                                                <textarea class="form-control text-box single-line" id="items_description" name="items_description" type="text" value="">@Model.newsDescription</textarea>
                                                <span class="field-validation-valid text-danger" data-valmsg-for="items_description" data-valmsg-replace="true"></span>
                                            </div>
                                        </div>
                                        
                                      <div class="form-group">
                                            <label class="control-label col-md-2" for="category_id">Category</label>
                                            <div class="col-md-10">
                                                @Html.DropDownList("category_id", null,"Select Category", htmlAttributes: new { @class = "form-control" })
                                                @Html.ValidationMessageFor(model => model.category_id, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                        
                                       <div class="form-group">
                                            <div class="thumbnail g-logo-img ">
                                                @{ var m = Model.news_img != null ? Model.news_img : "Product_Icon.png"; }
                                                <img id="image" src="~/Uploads/@m" + alt="" style="width: 150px; height: 150px;">
                                            </div>
                                            <label class="control-label col-md-2" for="items_img">Banner</label>
                                            <div class="input-group">
                                                <div class="custom-file">
                                                    <input type="hidden" value="@Model.news_img"/> 
                                                    <input type="file" class="custom-file-input" id="items_img"  name="items_img" onchange="readURL(this);">
                                                    <span class="field-validation-valid text-danger" data-valmsg-for="items_img" data-valmsg-replace="true"></span>
                                                    <label class="custom-file-label" for="items_img">@Model.news_img</label>
                                                </div>
                                                <div class="input-group-append">
                                                    <span class="input-group-text" id="">Upload</span>
                                                </div>
                                            </div>
                                        </div>
                                        
                                        <div class="form-group">
                                            <div class="col-md-offset-2 col-md-10">
                                                <input type="submit" value="Save" class="btn btn-default" />
                                            </div>
                                        </div>
                                    </div>
                                }
                            </div>
                            <!-- /.card-body -->
                        </div>
                        <!-- /.card -->
                    </div>
                    <!--/.col (left) -->
                </div>
                <!-- /.row -->
            </div><!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

News Online/OnlineNews/OnlineNews/Views/news/backend/Index.cshtml
@using System.Security.Cryptography.X509Certificates
@model OnlineNews.news

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout_backend.cshtml";
    int count = 1;
}
@{OnlineNewsEntities db = new OnlineNewsEntities();}


<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper" style="min-height: 512px;">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>@TempData["mainHead"]</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">@TempData["breadcrumb"]</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
        <div class="row">
            <!-- left column -->
            <div class="col-md-12">
                <!-- Form Element sizes -->
                <div class="card card-success">
                    <div class="card-header">
                        <h3 class="card-title">@TempData["cardTitle"]</h3>
                    </div>
                    <div class="card-body">
                        @Html.ActionLink("Create New", "Create",null,htmlAttributes: new {@class="btn btn-default", style="margin-bottom:10px;"})

                        <table id="datatable" class="table table-bordered table-striped">
                            <thead>
                            <tr>
                                <th>#SN</th>
                                <th>Image</th>
                                <th>News Title</th>
                                <th>Description</th>
                                <th>Category</th>
                                <th>Created By</th>
                                <th>Created On</th>

                            </tr>
                            </thead>
                            <tbody>
                            @foreach (var item in db.news)
                            {

                                <tr>
                                    <td>@count</td>
                                    <td><img src="~/Uploads/@item.news_img" alt="@item.news_img" width="50px" height="50px" /></td>
                                    <td>@item.newsTitle</td>
                                    <td>@item.newsDescription</td>
                                    <td>@item.category_id</td>
                                    <td>@item.createdby</td>
                                    <td>@item.createdDate</td>
                                    <td>
                                        <a href="/news/Edit/@item.id"><i class="fa fa-edit text-warning"></i></a>
                                        <a href="/news/Delete/@item.id"><i class="fa fa-trash text-danger"></i></a>
                                    </td>
                                    @{ count++;}
                                </tr>
                            }

                        </table>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
</div>
<!-- /.content -->
<p>
    @*@Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
        @Html.ActionLink("Back to List", "Index")*@
</p>